name: edna
version: 1.0.0
profile: edna

config-version: 2

# ---------------------------------------
#  FOLDER → SCHEMA LOGIC (Your Requirement)
# ---------------------------------------
models:
  edna:
    source:
      sales:
        +database: DBO_PROD
        +schema: SALES
      retail:
        +database: DBO_PROD
        +schema: RETAIL

    intermediate:
      sales:
        +database: DBO_PROD
        +schema: SALES
      retail:
        +database: DBO_PROD
        +schema: RETAIL

    mart:
      sales:
        +database: DBO_PROD
        +schema: SALES
      retail:
        +database: DBO_PROD
        +schema: RETAIL
