name: 'edna'
version: '1.4.7'
config-version: 2

profile: 'default'

models:
  +bind: false

  edna:

    # -------------------------------
    # STAGING MODELS (VIEW)
    # -------------------------------
    staging:
      +materialized: view

      sales:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'SALES' }}"

      retail:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'RETAIL' }}"

      finance:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'FINANCE' }}"

      hr:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'HR' }}"

    # -------------------------------
    # INTERMEDIATE MODELS (VIEW)
    # -------------------------------
    intermediate:
      +materialized: view

      sales:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'SALES' }}"

      retail:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'RETAIL' }}"

      finance:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'FINANCE' }}"

    # -------------------------------
    # MART MODELS (TABLE)
    # -------------------------------
    marts:
      +materialized: table

      sales:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'SALES' }}"

      retail:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'RETAIL' }}"

      finance:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'FINANCE' }}"

      hr:
        +schema: "{{ 'RVATS' if target.name != 'prod' else 'HR' }}"
